sudo: required
services:
  - docker

before_install:
  - docker build -t dockerleho8808g/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dockerleho8808g/react-test npm test

after_success:
  - docker build -t dockerleho8808g/multi-client ./client
  - docker build -t dockerleho8808g/multi-nginx ./nginx
  - docker build -t dockerleho8808g/multi-server ./server
  - docker build -t dockerleho8808g/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push the to dockerHub
  - docker push dockerleho8808g/multi-client 
  - docker push dockerleho8808g/multi-nginx 
  - docker push dockerleho8808g/multi-server 
  - docker push dockerleho8808g/multi-worker 
