sudo: required
services:
  - docker

before_install:
  - docker build -t leho8808/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run leho8808/react-test npm run test -- --coverage

after_success:
  - docker build -t leho8808/multi-client ./client
  - docker build -t leho8808/multi-nginx ./nginx
  - docker build -t leho8808/multi-server ./server
  - docker build -t leho8808/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push the to dockerHub
  - docker push leho8808/multi-client ./client
  - docker push leho8808/multi-nginx ./nginx
  - docker push leho8808/multi-server ./server
  - docker push leho8808/multi-worker ./worker
